Use tracex for all otel needs
snabble/go-logging pull request #55
Opened 2022-12-15 15:56 UTC by tnicolaisen-snabble

This depends on https://github.com/snabble/go-utils/pull/91 landing first.

The goal is that getting the otel dependencies via tracex can help us conduct what version of all the otel libraries we use in our services. We've seen in the past that there can be trouble with conflicting versions.

2022-12-16 08:31 UTC, g-w requested changes
* `tracex` requires go 1.19

2022-12-16 08:56 UTC, J-Rocke approved these changes

2022-12-19 09:31 UTC, tnicolaisen-snabble commented
Currently blocked by go-logging not having the SSH key to clone from our private repositories (see f.ex. the ssh key that coredata-service has here: https://app.travis-ci.com/github/snabble/coredata-service/settings ).

Also, it's not so sensible to have go-logging, a public repo, have dependency on a private repo (go-utils). We could consider open-sourcing go-utils. Or making go-logging private

2023-01-30 11:40 UTC, tnicolaisen-snabble commented
Just noticed that this one is still waiting to be unblocked.

Recapping the options:

- [ ] make go-logging private
- [ ] open-sourcing go-utils/tracex
- [ ] move go-utils/tracex into go-logging

2023-02-06 12:13 UTC, J-Rocke approved these changes

2023-02-06 14:41 UTC, merged